/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Rocket/Card.vue')['default']
    Detail: typeof import('./src/components/Rocket/Detail.vue')['default']
    Filter: typeof import('./src/components/Rocket/Filter.vue')['default']
    Form: typeof import('./src/components/Rocket/Form.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UIState: typeof import('./src/components/UIState.vue')['default']
  }
}
